import parse, { HTMLReactParserOptions } from 'html-react-parser';
import { FeaturedProducts, HeroCarousel } from '@/components/home';
import { TestimonialsCarousel } from '@/components/home';
import CollectionsCarousel from '@/components/home/CollectionsCarousel';
import ReviewsListWidget from '@/components/blocks/ReviewsListWidget';
import { ProductSlider3D } from '@/components/blocks/ProductSlider3D';
import { SpotlightSection } from '@/components/home/SpotlightSection';

/**
 * Property definitions for the TemplateInjector utility.
 */
interface TemplateInjectorProps {
    html: string;
    /** Optional product context used specifically for hydration within dynamic product template wrappers */
    productData?: any; 
    isStaticPage?: boolean;
    preloadedHero?: any;
    preloadedSpotlight?: any;
}

/**
 * Recursively checks if a DOM node or any of its children contains a specific data-widget name.
 */
function hasWidget(node: any, widgetName: string): boolean {
    if (!node) return false;
    if (node.attribs && node.attribs['data-widget'] === widgetName) {
        return true;
    }
    if (node.children && Array.isArray(node.children)) {
        for (const child of node.children) {
            if (hasWidget(child, widgetName)) {
                return true;
            }
        }
    }
    return false;
}

/**
 * Performs real-time server/client-side HTML hydration, locating custom custom block attributes
 * (data-widgets) generated by the Visual CMS editor, and seamlessly swapping those DOM anchors for
 * active, stateful React Components.
 */
export function TemplateInjector({ html, productData, isStaticPage, preloadedHero, preloadedSpotlight }: TemplateInjectorProps) {
    const options: HTMLReactParserOptions = {
        replace: (domNode) => {
            if (domNode.type === 'tag') {
                const element = domNode as any;
                if (!element.attribs) return;
 
                // Hide "Top Collections" section header on mobile
                const isHeading = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span'].includes(element.name);
                const textContent = element.children?.map((c: any) => c.data || c.children?.[0]?.data || '').join('').toUpperCase() || '';
                if (isHeading && textContent.includes('TOP COLLECTIONS')) {
                    const originalClass = element.attribs.class || '';
                    if (!originalClass.includes('hidden')) {
                        element.attribs.class = `${originalClass} hidden md:block`.trim();
                    }
                }

                // 1. Top Collections Section Matching
                if (element.name === 'div' && hasWidget(element, 'collection-list')) {
                    const originalClass = element.attribs.class || '';
                    if (!originalClass.includes('mobile-order-2')) {
                        element.attribs.class = `${originalClass} mobile-order-2`.trim();
                    }
                }

                // Optimize "Explore" title container margin bottom on mobile
                if (element.name === 'div' && (element.attribs.class || '').includes('text-center mb-4 md:mb-6')) {
                    element.attribs.class = element.attribs.class.replace('mb-4 md:mb-6', 'mb-2 md:mb-6');
                }

                // 2. Best Selling Products Section Matching
                if (element.name === 'div' && hasWidget(element, 'product-grid')) {
                    const originalClass = element.attribs.class || '';
                    if (!originalClass.includes('mobile-order-4')) {
                        element.attribs.class = `${originalClass} mobile-order-4`.trim();
                    }
                }
 
                // Optimize "Best Selling Products" title margin bottom on mobile
                if (element.name === 'h2' && textContent.includes('BEST SELLING PRODUCTS')) {
                    const originalClass = element.attribs.class || '';
                    if (originalClass.includes('mb-4')) {
                        element.attribs.class = originalClass.replace('mb-4', 'mb-2 md:mb-4');
                    }
                }

                // Add bottom margin to "See All Products" button on mobile to prevent overlapping with testimonials
                if (element.name === 'a' && (element.attribs.href === '/shop' || textContent.includes('SEE ALL PRODUCTS'))) {
                    const originalClass = element.attribs.class || '';
                    if (originalClass.includes('mt-4') && !originalClass.includes('mb-8')) {
                        element.attribs.class = originalClass.replace('mt-4', 'mt-4 mb-8 md:mb-0');
                    }
                }

                // 3. Testimonials Section Matching (What They Say / Our Customers Say)
                if (element.name === 'div' && (hasWidget(element, 'testimonials') || textContent.includes('TESTIMONIALS') || textContent.includes('CUSTOMERS SAY') || textContent.includes('WHAT THEY SAY'))) {
                    const originalClass = element.attribs.class || '';
                    if (!originalClass.includes('mobile-order-5')) {
                        element.attribs.class = `${originalClass} mobile-order-5`.trim();
                    }
                }

                // 4. About Us Section Matching
                if (element.name === 'div' && (textContent.includes('THE ESSENCE OF SALAF') || textContent.includes('DISCOVER OUR STORY') || (element.attribs.class || '').includes('py-12 md:py-24 bg-white'))) {
                    let originalClass = element.attribs.class || '';
                    if (!originalClass.includes('px-')) {
                        originalClass = `${originalClass} px-5 md:px-8`.trim();
                    }
                    if (!originalClass.includes('mobile-order-6')) {
                        originalClass = `${originalClass} mobile-order-6`.trim();
                    }
                    element.attribs.class = originalClass;
                }

                // Reduce empty space between text and image in "Discover Our Story" section
                if (element.name === 'div' && (element.attribs.class || '').includes('gap-12 md:gap-24')) {
                    element.attribs.class = element.attribs.class.replace('gap-12 md:gap-24', 'gap-4 md:gap-8');
                }
                if (element.name === 'div' && (element.attribs.class || '').includes('flex justify-center') && (element.attribs.class || '').includes('order-1 md:order-2')) {
                    element.attribs.class = element.attribs.class.replace('flex justify-center', 'flex justify-center md:justify-end');
                }

                // 5. Hide empty GrapesJS row spacer under Top Collections
                if (element.name === 'div' && element.attribs.id === 'ih177') {
                    const originalClass = element.attribs.class || '';
                    if (!originalClass.includes('hidden')) {
                        element.attribs.class = `${originalClass} hidden md:block`.trim();
                    }
                }
 
                // Dynamic Product Grid Hydration
                if (element.attribs['data-widget'] === 'product-grid') {
                    const sort = element.attribs['data-sort'] || 'recent';
                    const limit = parseInt(element.attribs['data-limit'] || '4', 10);
                    const collectionSlug = element.attribs['data-collection'] || '';
                    const colsDesktop = element.attribs['data-cols-desktop'] || '4';
                    const colsTablet = element.attribs['data-cols-tablet'] || '2';
                    const colsMobile = element.attribs['data-cols-mobile'] || '1';
 
                    const GridComponent = <FeaturedProducts data={{
                        limit,
                        sort,
                        collectionSlug,
                        gridCols: {
                            desktop: colsDesktop,
                            tablet: colsTablet,
                            mobile: colsMobile
                        }
                    } as any} isWidget={true} />;
 
                    if (!element.children || element.children.length === 0) {
                        return <div className="w-full">{GridComponent}</div>;
                    }
 
                    let replacedPrototype = false;
                    const { domToReact } = require('html-react-parser');
 
                    const newChildren = element.children.map((child: any, i: number) => {
                        const isTextNode = child.type === 'text' && child.data?.toUpperCase().includes('PROTOTYPE');
                        const isSpanWithText = child.type === 'tag' && child.children?.[0]?.type === 'text' && child.children[0].data?.toUpperCase().includes('PROTOTYPE');
 
                        if (!replacedPrototype && (isTextNode || isSpanWithText)) {
                            replacedPrototype = true;
                            return <div key={i} className="w-full my-0 sm:my-1">{GridComponent}</div>;
                        }
 
                        return domToReact([child], options);
                    });
 
                    if (!replacedPrototype) {
                        newChildren.push(<div key="grid-fallback" className="w-full my-0 sm:my-1">{GridComponent}</div>);
                    }

                    let wrapperClass = (element.attribs.class || '').replace(/border-2|border-dashed|bg-bprimary\/5|border-bprimary\/50|border-emerald-500\/50/g, ' ');

                    return (
                        <div className={`w-full ${wrapperClass}`}>
                            {newChildren}
                        </div>
                    );
                }

                // Testimonials Slider Hydration
                if (element.attribs['data-widget'] === 'testimonials') {
                    const limit = parseInt(element.attribs['data-limit'] || '20', 10);
                    return <TestimonialsCarousel limit={limit} />;
                }

                // Landing Hero Slider Hydration
                if (element.attribs['data-widget'] === 'hero-carousel') {
                    return <div className="mobile-order-1 w-full"><HeroCarousel preloadedData={preloadedHero} /></div>;
                }

                // Spotlight Section Hydration
                if (element.attribs['data-widget'] === 'spotlight') {
                    return <div className="mobile-order-3 w-full"><SpotlightSection preloadedData={preloadedSpotlight} /></div>;
                }

                // Interactive 3D Carousel Hydration
                if (element.attribs['data-widget'] === 'product-slider-3d') {
                    const title = element.attribs['data-title'] || "Weekly Bestsellers";
                    const productSlugs = element.attribs['data-products'] || "";
                    return <ProductSlider3D title={title} productSlugs={productSlugs} />;
                }

                // Featured Collection Links
                if (element.attribs['data-widget'] === 'collection-list') {
                    return <CollectionsCarousel />;
                }

                // User Verified Reviews List
                if (element.attribs['data-widget'] === 'reviews-list') {
                    const limit = parseInt(element.attribs['data-limit'] || '12', 10);
                    return <ReviewsListWidget limit={limit} />;
                }

                // Core product display area for default dynamic PDP layouts
                if (element.attribs['data-widget'] === 'product-core') {
                    if (!productData) return <div className="p-4 bg-red-500/10 text-red-500">Missing valid product context</div>;

                    return (
                        <div className="w-full relative">
                            {/* Inner layout structure is derived from default product template settings */}
                        </div>
                    );
                }
            }
        }
    };

    let cleanHtml = html || '';

    // Extract body node boundaries from Visual CMS exports to maintain correct React root hierarchy
    const bodyMatch = cleanHtml.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
    if (bodyMatch) {
        cleanHtml = bodyMatch[1];
    } else {
        cleanHtml = cleanHtml.replace(/<\/?html[^>]*>/gi, '')
            .replace(/<head[^>]*>[\s\S]*?<\/head>/gi, '');
    }

    let reactElements;
    try {
        reactElements = parse(cleanHtml, options);
    } catch (e) {
        reactElements = <div>Failed to parse storefront layout template.</div>;
    }

    return (
        <div className={`theme-builder-content w-full max-w-full overflow-x-hidden p-0 m-0 ${isStaticPage ? 'static-page-wrapper' : ''}`}>
            {reactElements}
        </div>
    );
}
